name: ladder
on:
  push:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  update-ladder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
      - name: Refresh ladder
        run: python3 ladder.py
      - name: Push if there are changes
        continue-on-error: true
        run: >-
          git config --global user.name 'GitHub Action';
          git config --global user.email 'github-action@users.noreply.github.com';
          git add docs/data results;
          author=$(git log --format='%ae' -1);
          if [[ "$author" != 'github-action@users.noreply.github.com' ]];
          then
            git commit -m "Update for `date -I`.";
          else
            message=$(git log --format='%s' -1);
            git commit --amend -m "${message::21} to `date -I`.";
          fi;
          git push -f;
